---
## Default Kibana configuration from kibana-docker.
## from https://github.com/elastic/kibana-docker/blob/master/build/kibana/config/kibana.yml
#
server.name: kibana
server.host: "0"
elasticsearch.url: http://192.168.3.237:9200
#logging.dest: /var/log/kibana/kibana.log
#monitoring.ui.container.elasticsearch.enabled: true
